{
  "hash": "d54219f802b99ee16febe11ebb8e5f12",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"DESEq2 workflow\"\noutput: html_notebook\n---\n\n# DESEq2 vignette\n\nIf you have any questions, check the [DESEq2 vignette](https://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html).\n\n# About the dataset\n\nThis workflow uses the **airway** dataset (Bioconductor package `airway`), an RNA-seq experiment from [Himes et al. 2014, *PLoS ONE*](https://doi.org/10.1371/journal.pone.0099625) (GEO: [GSE52778](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52778)).\nThe code used to generate the tables can be found [Jieyin-Training/data/airway_generate_counts.R](../data/airway_generate_counts.R)\n\n- **Biological question:** how do human airway smooth muscle (ASM) cells respond to dexamethasone, a glucocorticoid used to treat asthma and inflammation?\n- **Design:** four ASM cell lines (`N61311`, `N052611`, `N080611`, `N061011`), each either left untreated (`untrt`) or treated with dexamethasone (`trt`).\n- **Size:** 8 samples (4 cell lines x 2 conditions) and 63,677 genes.\n- **Count matrix** (`airway_raw_counts.csv`): rows are genes (Ensembl IDs), columns are samples (SRA run IDs, e.g. `SRR1039508`). Values are raw, unnormalized read counts.\n- **Metadata** (`airway_metadata.csv`): one row per sample.\n  - `cell`: the cell line.\n  - `dex`: dexamethasone treatment (`trt` / `untrt`). This is the main variable of interest.\n  - `albut`: albuterol treatment. Every sample here is `untrt`, so it carries no information.\n  - `SampleName`, `Run`, `Experiment`, `Sample`, `BioSample`: GEO / SRA identifiers.\n  - `avgLength`: average read length.\n\nFull description:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(airway)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: SummarizedExperiment\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: MatrixGenerics\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: pakiet 'MatrixGenerics' zostal zbudowany w wersji R 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: matrixStats\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nDolaczanie pakietu: 'MatrixGenerics'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNastepujace obiekty zostaly zakryte z 'package:matrixStats':\n\n    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,\n    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,\n    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,\n    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,\n    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,\n    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,\n    colWeightedMeans, colWeightedMedians, colWeightedSds,\n    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,\n    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,\n    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,\n    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,\n    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,\n    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,\n    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,\n    rowWeightedSds, rowWeightedVars\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: GenomicRanges\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: stats4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: BiocGenerics\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nDolaczanie pakietu: 'BiocGenerics'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNastepujace obiekty zostaly zakryte z 'package:stats':\n\n    IQR, mad, sd, var, xtabs\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNastepujace obiekty zostaly zakryte z 'package:base':\n\n    Filter, Find, Map, Position, Reduce, anyDuplicated, aperm, append,\n    as.data.frame, basename, cbind, colnames, dirname, do.call,\n    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,\n    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,\n    pmin.int, rank, rbind, rownames, sapply, saveRDS, setdiff, table,\n    tapply, union, unique, unsplit, which.max, which.min\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: S4Vectors\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nDolaczanie pakietu: 'S4Vectors'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNastepujacy obiekt zostal zakryty z 'package:utils':\n\n    findMatches\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNastepujace obiekty zostaly zakryte z 'package:base':\n\n    I, expand.grid, unname\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: IRanges\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: pakiet 'IRanges' zostal zbudowany w wersji R 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: GenomeInfoDb\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: pakiet 'GenomeInfoDb' zostal zbudowany w wersji R 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLadowanie wymaganego pakietu: Biobase\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to Bioconductor\n\n    Vignettes contain introductory material; view with\n    'browseVignettes()'. To cite Bioconductor, see\n    'citation(\"Biobase\")', and for packages 'citation(\"pkgname\")'.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nDolaczanie pakietu: 'Biobase'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNastepujacy obiekt zostal zakryty z 'package:MatrixGenerics':\n\n    rowMedians\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNastepujace obiekty zostaly zakryte z 'package:matrixStats':\n\n    anyMissing, rowMedians\n```\n\n\n:::\n\n```{.r .cell-code}\nvignette(\"airway\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nuruchamianie serwera httpd dla pomocy ...\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n wykonano\n```\n\n\n:::\n:::\n\n\nBecause each cell line appears in both conditions, the design is **paired**.\nIn the DESeq2 model, `cell` should be included as a covariate alongside `dex`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(DESeq2)\nlibrary(annotables)\nlibrary(PCAtools)\n```\n:::\n\n\n# Import the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_counts <- read.csv(\"data/airway_raw_counts.csv\", row.names = 1)\nmtd <- read.csv(\"data/airway_metadata.csv\", row.names = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(raw_counts)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"SRR1039508\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039509\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039512\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039513\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039516\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039517\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039520\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039521\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"679\",\"2\":\"448\",\"3\":\"873\",\"4\":\"408\",\"5\":\"1138\",\"6\":\"1047\",\"7\":\"770\",\"8\":\"572\",\"_rn_\":\"ENSG00000000003\"},{\"1\":\"0\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\",\"_rn_\":\"ENSG00000000005\"},{\"1\":\"467\",\"2\":\"515\",\"3\":\"621\",\"4\":\"365\",\"5\":\"587\",\"6\":\"799\",\"7\":\"417\",\"8\":\"508\",\"_rn_\":\"ENSG00000000419\"},{\"1\":\"260\",\"2\":\"211\",\"3\":\"263\",\"4\":\"164\",\"5\":\"245\",\"6\":\"331\",\"7\":\"233\",\"8\":\"229\",\"_rn_\":\"ENSG00000000457\"},{\"1\":\"60\",\"2\":\"55\",\"3\":\"40\",\"4\":\"35\",\"5\":\"78\",\"6\":\"63\",\"7\":\"76\",\"8\":\"60\",\"_rn_\":\"ENSG00000000460\"},{\"1\":\"0\",\"2\":\"0\",\"3\":\"2\",\"4\":\"0\",\"5\":\"1\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\",\"_rn_\":\"ENSG00000000938\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nCount matrix is a table where rows correspond to gene names and columns - to samples.\nThe gene names are encoded in \"ENSEMBL\" system.\nWe will convert those names to SYMBOLs - regular gene names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mtd)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"SampleName\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cell\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"dex\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"albut\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Run\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"avgLength\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Experiment\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sample\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"BioSample\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"GSM1275862\",\"2\":\"N61311\",\"3\":\"untrt\",\"4\":\"untrt\",\"5\":\"SRR1039508\",\"6\":\"126\",\"7\":\"SRX384345\",\"8\":\"SRS508568\",\"9\":\"SAMN02422669\",\"_rn_\":\"SRR1039508\"},{\"1\":\"GSM1275863\",\"2\":\"N61311\",\"3\":\"trt\",\"4\":\"untrt\",\"5\":\"SRR1039509\",\"6\":\"126\",\"7\":\"SRX384346\",\"8\":\"SRS508567\",\"9\":\"SAMN02422675\",\"_rn_\":\"SRR1039509\"},{\"1\":\"GSM1275866\",\"2\":\"N052611\",\"3\":\"untrt\",\"4\":\"untrt\",\"5\":\"SRR1039512\",\"6\":\"126\",\"7\":\"SRX384349\",\"8\":\"SRS508571\",\"9\":\"SAMN02422678\",\"_rn_\":\"SRR1039512\"},{\"1\":\"GSM1275867\",\"2\":\"N052611\",\"3\":\"trt\",\"4\":\"untrt\",\"5\":\"SRR1039513\",\"6\":\"87\",\"7\":\"SRX384350\",\"8\":\"SRS508572\",\"9\":\"SAMN02422670\",\"_rn_\":\"SRR1039513\"},{\"1\":\"GSM1275870\",\"2\":\"N080611\",\"3\":\"untrt\",\"4\":\"untrt\",\"5\":\"SRR1039516\",\"6\":\"120\",\"7\":\"SRX384353\",\"8\":\"SRS508575\",\"9\":\"SAMN02422682\",\"_rn_\":\"SRR1039516\"},{\"1\":\"GSM1275871\",\"2\":\"N080611\",\"3\":\"trt\",\"4\":\"untrt\",\"5\":\"SRR1039517\",\"6\":\"126\",\"7\":\"SRX384354\",\"8\":\"SRS508576\",\"9\":\"SAMN02422673\",\"_rn_\":\"SRR1039517\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nMetadata contains information about samples.\nEach row is a sample and each column describes a metric.\nFor example, we can put information about treatment, batch, collection date, patient ID, etc.\n\nIt is important that the count table and metadata are matching.\nColumn names of the count matrix and row names of the metadata have to be the same!\n\nWe can ensure those two are matching by running this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall(rownames(mtd) == colnames(raw_counts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nif they're not in the right order we can use `match()` to reorder one table so it lines up with the other:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_counts <- raw_counts[, match(rownames(mtd), colnames(raw_counts))]\n```\n:::\n\n\n# Pre–filtering\n\n## Remove low count genes\n\nIt is not necessary to filter out low count genes, because DESEq pipeline does it automatically (`independent filtering`), but applying a small cutoff might make the object smaller and require less computational power and memory.\nThis cutoff is taken from the vignette.\nIt's also common to use `filterByExp` from edgeR package\n\n`smallestGroupSize` - we have 4 treated and 4 controls so we will use 4.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(mtd$dex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  trt untrt \n    4     4 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nngenes_before <- nrow(raw_counts)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmallestGroupSize <- 4\nkeep <- rowSums(raw_counts >= 10) >= smallestGroupSize\nraw_counts <- raw_counts[keep,]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nngenes_after <- nrow(raw_counts)\ncat(\"#genes before filtering: \", ngenes_before, \"\\n #genes after filtering: \", ngenes_after)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#genes before filtering:  63677 \n #genes after filtering:  16139\n```\n\n\n:::\n:::\n\n\n1.  `raw_counts >= 10` gives a table of TRUE/FALSE with the same shape as the counts. Each cell asks whether this gene had at least 10 reads in this sample.\n2.  `rowSums(...)` adds up the TRUE values for each gene, giving the number of samples where the gene reached 10 reads.\n3.  `>= smallestGroupSize` asks whether that number is at least the size of your smallest experimental group.\n\nA gene that is truly different between conditions should have decent counts in all the samples of at least one group.\nIf your smallest group has 4 samples, requiring at least 4 samples with 10 or more reads means a gene could pass by being expressed in just one condition, such as a gene that is switched on only after treatment.\nA gene with high counts in only 1 of 8 samples is most likely noise or an outlier, so it is dropped.\n\n## Convert ENSEMBL to SYMBOL\n\nBefore we do any analysis, we need to do a little bit of a cleanup.\n\nFirst we need to convert the ENS to SYMBOL.\nWe will use `annotables` package, that provides per gene information for different genome versions.\n`airway` dataset uses Grch37 genome assembly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(grch37)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ensgene\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"entrez\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"symbol\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"chr\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"start\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"end\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"strand\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"biotype\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"description\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"ENSG00000000003\",\"2\":\"7105\",\"3\":\"TSPAN6\",\"4\":\"X\",\"5\":\"99883667\",\"6\":\"99894988\",\"7\":\"-1\",\"8\":\"protein_coding\",\"9\":\"tetraspanin 6\"},{\"1\":\"ENSG00000000005\",\"2\":\"64102\",\"3\":\"TNMD\",\"4\":\"X\",\"5\":\"99839799\",\"6\":\"99854882\",\"7\":\"1\",\"8\":\"protein_coding\",\"9\":\"tenomodulin\"},{\"1\":\"ENSG00000000419\",\"2\":\"8813\",\"3\":\"DPM1\",\"4\":\"20\",\"5\":\"49551404\",\"6\":\"49575092\",\"7\":\"-1\",\"8\":\"protein_coding\",\"9\":\"dolichyl-phosphate mannosyltransferase polypeptide 1, catalytic subunit\"},{\"1\":\"ENSG00000000457\",\"2\":\"57147\",\"3\":\"SCYL3\",\"4\":\"1\",\"5\":\"169818772\",\"6\":\"169863408\",\"7\":\"-1\",\"8\":\"protein_coding\",\"9\":\"SCY1-like 3 (S. cerevisiae)\"},{\"1\":\"ENSG00000000460\",\"2\":\"55732\",\"3\":\"C1orf112\",\"4\":\"1\",\"5\":\"169631245\",\"6\":\"169823221\",\"7\":\"1\",\"8\":\"protein_coding\",\"9\":\"chromosome 1 open reading frame 112\"},{\"1\":\"ENSG00000000938\",\"2\":\"2268\",\"3\":\"FGR\",\"4\":\"1\",\"5\":\"27938575\",\"6\":\"27961788\",\"7\":\"-1\",\"8\":\"protein_coding\",\"9\":\"feline Gardner-Rasheed sarcoma viral oncogene homolog\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nWe will use this table to build our own gene annotation table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_anno <- data.frame(ensgene = rownames(raw_counts)) %>%\n  left_join(grch37, by= \"ensgene\") %>%\n  distinct(symbol, .keep_all = TRUE) %>% # sometimes one ENSEMBL might have two different SYMBOLs or ENTREZ. It might happen where there are multiple isoforms of one gene etc. This makes sure that when an ENS is doubled, we only take the first observation.\n  rename(gene_start = start, gene_end = end, gene_strand = strand) # start/end/strand are reserved names in rowData (GRanges), so DESeq2 would error\n```\n:::\n\n\n## Retain only protein coding genes\n\nAs you can see there are more than 60,000 genes in our dataset (before filtering).\nHuman genome has around 20,000 genes, so how is it possible?\nLet's investigate `biotype` column\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(gene_anno$biotype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n3prime_overlapping_ncRNA                  Mt_rRNA                  Mt_tRNA \n                       1                        2                        3 \n               TR_C_gene                antisense                  lincRNA \n                       1                      635                      662 \n                   miRNA                 misc_RNA   polymorphic_pseudogene \n                      13                       13                       10 \n    processed_transcript           protein_coding               pseudogene \n                     141                    13055                     1461 \n                    rRNA           sense_intronic        sense_overlapping \n                       3                       64                       53 \n                   snRNA                   snoRNA \n                       1                        4 \n```\n\n\n:::\n:::\n\n\nA lot of the transcripts are not even protein coding genes.\nLots of them are non-coding RNA, rRNA etc.\nIn this analysis we only care about protein coding genes.\n\nFirst we will subset `gene_anno` to only protein coding genes and use that table to subset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_anno <- gene_anno %>%\n  filter(biotype == 'protein_coding')\ndim(gene_anno)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13055     9\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_counts <- raw_counts[gene_anno$ensgene, ] # retain only protein coding genes\nrownames(raw_counts) <- gene_anno$symbol # replace ENS with symbols count table\nrownames(gene_anno) <- gene_anno$symbol\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(raw_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13055     8\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(raw_counts)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"SRR1039508\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039509\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039512\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039513\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039516\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039517\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039520\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SRR1039521\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"679\",\"2\":\"448\",\"3\":\"873\",\"4\":\"408\",\"5\":\"1138\",\"6\":\"1047\",\"7\":\"770\",\"8\":\"572\",\"_rn_\":\"TSPAN6\"},{\"1\":\"467\",\"2\":\"515\",\"3\":\"621\",\"4\":\"365\",\"5\":\"587\",\"6\":\"799\",\"7\":\"417\",\"8\":\"508\",\"_rn_\":\"DPM1\"},{\"1\":\"260\",\"2\":\"211\",\"3\":\"263\",\"4\":\"164\",\"5\":\"245\",\"6\":\"331\",\"7\":\"233\",\"8\":\"229\",\"_rn_\":\"SCYL3\"},{\"1\":\"60\",\"2\":\"55\",\"3\":\"40\",\"4\":\"35\",\"5\":\"78\",\"6\":\"63\",\"7\":\"76\",\"8\":\"60\",\"_rn_\":\"C1orf112\"},{\"1\":\"3251\",\"2\":\"3679\",\"3\":\"6177\",\"4\":\"4252\",\"5\":\"6721\",\"6\":\"11027\",\"7\":\"5176\",\"8\":\"7995\",\"_rn_\":\"CFH\"},{\"1\":\"1433\",\"2\":\"1062\",\"3\":\"1733\",\"4\":\"881\",\"5\":\"1424\",\"6\":\"1439\",\"7\":\"1359\",\"8\":\"1109\",\"_rn_\":\"FUCA2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nWe are left with \\~13,000 genes\n\n# DESeq2 workflow: Part I\n\nWe prepared the metadata and count matrix.\nWe are ready to create a deseq object (`dds`).\nIT IS IMPORTANT THAT THE COUNTS ARE RAW!\nIf the counts are integers, they are most likely raw counts.\n\n## Design\n\nThe **design** is a formula that tells DESeq2 which factors may explain differences in gene expression between your samples.\nIt is written as `~ variable1 + variable2`, where each variable is a column name from the metadata table - just like linear regression.\n\n**Why is it important?** DESeq2 fits a model for every gene using the design.\nIt uses that model to separate the effect you care about (here, the drug) from other sources of variation (here, the cell line).\nIf the design is wrong or incomplete, the variation you did not account for stays in the noise.\nThat can hide real differences or create false ones.\nThe design cannot be fixed after the fact without re-running the analysis, so it is worth getting right before you create `dds`.\n\n**How do we decide what goes there?**\n\n1.  Start from your biological question. We want to know which genes change with dexamethasone, so `dex` goes in.\n2.  Add the other variables that are known to affect expression and that you want to correct for, such as cell line, batch, sex, or age. Here the same four cell lines appear both treated and untreated, and different cell lines naturally express genes differently, so `cell` goes in. This is called paired design.\n3.  Put the variable of interest **last**. DESeq2 tests the last variable in the formula by default.\n4.  Only use columns that exist in the metadata, and only the ones that matter. Identifiers (sample name, run ID) are different for every sample and must not go in the design. Variables that are constant (like `albut` here) carry no information. Don't add variables just because you have them, since each one uses up samples that could have gone into the real comparison.\n\nSo our design is `~ cell + dex`.\nIn plain words: \"compare treated and untreated samples, but control for individual effects of each cell line\").\n\n**Paired design:** the same cell line (or patient, animal, etc.) is measured in both conditions, so every treated sample has an untreated \"partner\".\n\n**Why control for it?** Cell lines differ from each other far more than we expect treatment to change a typical gene.\nIf `cell` is not in the design, that cell-to-cell variation lands in the noise, so real drug effects are harder to detect.\nWith `cell` in the design, we account for these cell-line specific effects, focusing on the drug effect.\n\n## Create a DESeq object\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds <- DESeqDataSetFromMatrix(countData = raw_counts, \n                              colData = mtd, \n                              rowData = gene_anno,\n                              design = ~ cell + dex)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in DESeqDataSet(se, design = design, ignoreRank): some variables in\ndesign formula are characters, converting to factors\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: DESeqDataSet \ndim: 13055 8 \nmetadata(1): version\nassays(1): counts\nrownames(13055): TSPAN6 DPM1 ... GTF2H5 NUDT3\nrowData names(9): ensgene entrez ... biotype description\ncolnames(8): SRR1039508 SRR1039509 ... SRR1039520 SRR1039521\ncolData names(9): SampleName cell ... Sample BioSample\n```\n\n\n:::\n:::\n\n\ndds object contains all this individual information and tables in one object.\nEach element can be accessed\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds@design\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n~cell + dex\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(dds@colData) # metadata\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDataFrame with 6 rows and 9 columns\n            SampleName     cell      dex       albut         Run avgLength\n           <character> <factor> <factor> <character> <character> <integer>\nSRR1039508  GSM1275862  N61311     untrt       untrt  SRR1039508       126\nSRR1039509  GSM1275863  N61311     trt         untrt  SRR1039509       126\nSRR1039512  GSM1275866  N052611    untrt       untrt  SRR1039512       126\nSRR1039513  GSM1275867  N052611    trt         untrt  SRR1039513        87\nSRR1039516  GSM1275870  N080611    untrt       untrt  SRR1039516       120\nSRR1039517  GSM1275871  N080611    trt         untrt  SRR1039517       126\n            Experiment      Sample    BioSample\n           <character> <character>  <character>\nSRR1039508   SRX384345   SRS508568 SAMN02422669\nSRR1039509   SRX384346   SRS508567 SAMN02422675\nSRR1039512   SRX384349   SRS508571 SAMN02422678\nSRR1039513   SRX384350   SRS508572 SAMN02422670\nSRR1039516   SRX384353   SRS508575 SAMN02422682\nSRR1039517   SRX384354   SRS508576 SAMN02422673\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(counts(dds)) # counts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516 SRR1039517\nTSPAN6          679        448        873        408       1138       1047\nDPM1            467        515        621        365        587        799\nSCYL3           260        211        263        164        245        331\nC1orf112         60         55         40         35         78         63\nCFH            3251       3679       6177       4252       6721      11027\nFUCA2          1433       1062       1733        881       1424       1439\n         SRR1039520 SRR1039521\nTSPAN6          770        572\nDPM1            417        508\nSCYL3           233        229\nC1orf112         76         60\nCFH            5176       7995\nFUCA2          1359       1109\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(rowData(dds)) # gene_anno\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDataFrame with 6 rows and 9 columns\n                 ensgene    entrez      symbol         chr gene_start  gene_end\n             <character> <integer> <character> <character>  <integer> <integer>\nTSPAN6   ENSG00000000003      7105      TSPAN6           X   99883667  99894988\nDPM1     ENSG00000000419      8813        DPM1          20   49551404  49575092\nSCYL3    ENSG00000000457     57147       SCYL3           1  169818772 169863408\nC1orf112 ENSG00000000460     55732    C1orf112           1  169631245 169823221\nCFH      ENSG00000000971      3075         CFH           1  196621008 196716634\nFUCA2    ENSG00000001036      2519       FUCA2           6  143815948 143832827\n         gene_strand        biotype            description\n           <integer>    <character>            <character>\nTSPAN6            -1 protein_coding          tetraspanin 6\nDPM1              -1 protein_coding dolichyl-phosphate m..\nSCYL3             -1 protein_coding SCY1-like 3 (S. cere..\nC1orf112           1 protein_coding chromosome 1 open re..\nCFH                1 protein_coding    complement factor H\nFUCA2             -1 protein_coding fucosidase, alpha-L-..\n```\n\n\n:::\n:::\n\n\n## Running DESeq\n\n`DESeq()` this function does the following steps:\n\n1.  estimation of size factors - normalization\n2.  estimation of dispersion\n3.  Negative Binomial GLM fitting and Wald statistics - prepares for differential expression\n\nThese steps are basically normalization and preparation for differential expression testing (log2 fold change and p-value) and are almost always run with default parameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds <- DESeq(dds)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nestimating size factors\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nestimating dispersions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\ngene-wise dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nmean-dispersion relationship\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nfinal dispersion estimates\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nfitting model and testing\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: DESeqDataSet \ndim: 13055 8 \nmetadata(1): version\nassays(4): counts mu H cooks\nrownames(13055): TSPAN6 DPM1 ... GTF2H5 NUDT3\nrowData names(43): ensgene entrez ... deviance maxCooks\ncolnames(8): SRR1039508 SRR1039509 ... SRR1039520 SRR1039521\ncolData names(10): SampleName cell ... BioSample sizeFactor\n```\n\n\n:::\n:::\n\n\nYou can notice that after running this function, there are new elements added to the dds object: new assays, sizeFactor in colData etc.\nYou can also access normalized counts.\nNotice how they changed from integers to decimals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(counts(dds, normalize=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516 SRR1039517\nTSPAN6    667.30264  499.92596  747.72294  609.74013  971.13906  747.92120\nDPM1      458.95483  574.69167  531.88539  545.47830  500.93025  570.76317\nSCYL3     255.52089  235.45620  225.25903  245.09162  209.07651  236.44882\nC1orf112   58.96636   61.37484   34.25993   52.30614   66.56313   45.00385\nCFH      3194.99392 4105.41876 5290.58943 6354.44858 5735.52337 7877.10327\nFUCA2    1408.31322 1185.09234 1484.31139 1316.62023 1215.20388 1027.94519\n         SRR1039520 SRR1039521\nTSPAN6    841.76522  601.80928\nDPM1      455.86506  534.47398\nSCYL3     254.71597  240.93414\nC1orf112   83.08332   63.12685\nCFH      5658.41143 8411.65250\nFUCA2    1485.66096 1166.79457\n```\n\n\n:::\n\n```{.r .cell-code}\n# raw counts can still be obtained with\n# counts(dds, normalize=FALSE)\n```\n:::\n\n\n# Principal component analysis\n\nAfter RNA-seq you have a matrix of counts: 13,000 genes (rows) by 8 samples.\nEach sample is a point in 13,000-dimensional space, which you can't look at.\nBut many genes move together.\nFor example, hundreds of inflammation genes rise and fall as a group.\nSo the data really vary along far fewer independent directions than 13,000.\n\nPCA finds new axes, called principal components, that are weighted combinations of genes.\nPC1 is the single direction along which the samples spread out the most.\nPC2 is the next-most-variable direction, at right angles to PC1, and so on.\nPlotting each sample's position on PC1 against PC2 gives a scatterplot.\nSamples close together have similar overall expression profiles.\nThe axis labels report the percentage of total variance each PC captures, which tells you how much of the full picture the plot actually shows.\n\nPCA is a quality-control and exploration step.\nIt is *not* part of the differential expression test itself.\nYou use it to ask a few questions:\n\n- Do replicates of the same condition cluster together?\n\n- Does PC1 separate your biological groups (treated vs. control), or does it separate something unwanted, like sequencing batch, sex, or the day samples were processed?\n  If batch dominates, you'd add it to your design formula (`~ batch + condition`).\n\n- Is there an outlier sample that looks like neither group?\n\nPCA requires data transformation that is different that what we did with `DESeq()` function.\nWe need to apply variance-stabilizing transformation, which puts genes on a comparable scale.\nTo do so, we will use `vst()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvsd <- vst(dds, blind=FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvsd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: DESeqTransform \ndim: 13055 8 \nmetadata(1): version\nassays(1): ''\nrownames(13055): TSPAN6 DPM1 ... GTF2H5 NUDT3\nrowData names(43): ensgene entrez ... maxCooks dispFit\ncolnames(8): SRR1039508 SRR1039509 ... SRR1039520 SRR1039521\ncolData names(10): SampleName cell ... BioSample sizeFactor\n```\n\n\n:::\n:::\n\n\nI will show two methods of running PCA: one is built in DESeq2 and is simpler, and another using `PCAtools` package, which I prefer because it gives me more control.\n\n1.  DESeq default\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotPCA(vsd, intgroup=c(\"cell\", \"dex\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nusing ntop=500 top features by variance\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `aes_string()` was deprecated in ggplot2 3.0.0.\ni Please use tidy evaluation idioms with `aes()`.\ni See also `vignette(\"ggplot2-in-packages\")` for more information.\ni The deprecated feature was likely used in the DESeq2 package.\n  Please report the issue to the authors.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](DESeq2_workflow_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nThere is a message saying `using ntop=500 top features by variance`.\nMost of the genes are not highly variable across samples (e.g. house keeping genes) and they are not very informative of sample composition and sample-to-sample differences.\nThat's why we use a fraction genes with the highest variance - they are the most informative ones, because they vary the most across samples.\n`plotPCA` uses top 500 most highly variable genes by default.\n\n2.  Using `PCAtools`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvsd %>%\n  assay %>%\n  pca(., vsd@colData, removeVar = 0.9) %>% # remove 90% of lower variance -> retains top 10% most variable genes\n  biplot(colby = \"cell\",  shape = 'dex', legendPosition = 'right', lab = NULL )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n-- removing the lower 90% of variables based on variance\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.\ni Please use the `linewidth` argument instead.\ni The deprecated feature was likely used in the PCAtools package.\n  Please report the issue to the authors.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n* fill : \"\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](DESeq2_workflow_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nColor represents cell line and shape represents treatment status.\nThanks to this we can easily identify the main sources of variation:\n\n- PC1 explains 50% of variation and is driven by dex (treatment status) - triangles and dots are clearly separated on the X axis.\n  This is great, because it means that the treatment made a real difference\n\n- PC2 explains 20% variation and is driven by cell line - different colors separate along the Y axis, with the blue color separating the most from the rest.\n  It is expected to see such spread between biological replicates, because each replicate is a separate cell line.\n  There are differences in baseline expression between different cell lines, which is why we see such separation on PC2.\n  This is also why we included cell line in the design - we don't want the differences between cell lines mask the effect of treatment, especially in a paired design.\n\nWe can color or shape the plot by every variable that exist in our metadata column.\nIt is a good practice to play with them, because it might help identify sources of technical variability that can be accounted for in the DESeq design.\n\n# DESeq2 workflow: Part II\n\n## Differential expression test\n\nNow that we normalized the data and did a QC check with PCA, we can perform Differential Gene Expression - the clue of the analysis.\nIn DGE we look for differences in gene expression across two different conditions.\nFor example: Gene A is 2x highly expressed in the treated group than untreated.\nWe will use `results()` function that return a table with log2 fold change difference between group 1 and group 2 and a p-value.\nWe need to specify `contrast` which takes a vector of characters: `c(column in metadata, group 1, group 2)`.\nHere, we want to investigate the effect of dexamethasone treatment, so we will use dex column and compare trt vs. untrt\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeg_table <- results(dds, contrast = c(\"dex\", \"trt\", \"untrt\"), alpha = 0.05) # alpha is the p-value threshold to whether call a gene significant or not. \n```\n:::\n\n\nWe can obtain a summary of our results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(deg_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nout of 13055 with nonzero total read count\nadjusted p-value < 0.05\nLFC > 0 (up)       : 2023, 15%\nLFC < 0 (down)     : 1810, 14%\noutliers [1]       : 0, 0%\nlow counts [2]     : 0, 0%\n(mean count < 7)\n[1] see 'cooksCutoff' argument of ?results\n[2] see 'independentFiltering' argument of ?results\n```\n\n\n:::\n:::\n\n\nOut of 13055 tested genes 2023 are expressed higher after the treatment than in control (upregulated) and 1810 are expressed lower after the treatment than in the control (downregulated)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(deg_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2 fold change (MLE): dex trt vs untrt \nWald test p-value: dex trt vs untrt \nDataFrame with 6 rows and 6 columns\n          baseMean log2FoldChange     lfcSE      stat      pvalue        padj\n         <numeric>      <numeric> <numeric> <numeric>   <numeric>   <numeric>\nTSPAN6    710.9158     -0.3931908 0.0998361 -3.938363 8.20395e-05 5.63698e-04\nDPM1      521.6303      0.1949073 0.1111022  1.754306 7.93780e-02 1.86583e-01\nSCYL3     237.8129      0.0260166 0.1411996  0.184254 8.53814e-01 9.17415e-01\nC1orf112   58.0856     -0.1011193 0.2816812 -0.358985 7.19606e-01 8.35955e-01\nCFH      5828.5177      0.4144223 0.0882714  4.694864 2.66784e-06 2.57228e-05\nFUCA2    1286.2427     -0.2530304 0.0885088 -2.858817 4.25225e-03 1.78901e-02\n```\n\n\n:::\n:::\n\n\n`deg_table` is the main result of the analysis.\nIt has one row per gene and answers the question: \"did this gene change after dexamethasone treatment, and by how much?\" The columns are:\n\n- `baseMean` - average normalized expression of the gene across all samples. Tells you how highly the gene is expressed overall.\n- `log2FoldChange` - the size and direction of the change (treated vs. untreated). A value of 1 means 2x higher in treated, -1 means 2x lower, 0 means no change.\n- `lfcSE` - standard error of the log2 fold change, i.e. how uncertain that estimate is.\n- `stat` - the Wald test statistic (`log2FoldChange / lfcSE`). The p-value is derived from it.\n- `pvalue` - the probability of seeing a change at least this large if the gene was **not** truly affected by the treatment.\n- `padj` - the p-value adjusted for multiple testing. **This is the value to use to call genes significant.**\n\n## Adjusted p-value and multiple testing correction\n\nA p-value of 0.05 means that there is a 5% chance of getting a result this extreme just by luck, even if nothing is going on.\nThat is fine for one test, but here we test \\~13,000 genes at once.\nIf none of the genes were truly changed, we would still expect 0.05 × 13,000 = **\\~650 genes** with p \\< 0.05 purely by chance.\nThese false positives would be mixed in with the real hits, and we could not tell which are which.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(deg_table$pvalue < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4959\n```\n\n\n:::\n:::\n\n\nIf we hadn't correct the p-value for multiple testing, we would have to expect that 13% of \"significant\" genes could be actually not significant - false positive\n\n**Multiple testing correction** fixes this by making the threshold stricter the more genes we test.\nDESeq2 uses the Benjamini-Hochberg method, which controls the **false discovery rate (FDR)**.\nThe adjusted p-value (`padj`) is the expected proportion of false positives among the genes called significant at that cutoff.\nFor example, if we keep all genes with `padj` \\< 0.05, we accept that about 5% of them may be false positives.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n0.05 * sum(deg_table$padj < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 191.65\n```\n\n\n:::\n:::\n\n\nA useful metric or test to check if our differential expression test was well calibrated and the results are reliable is to look the distribution of nominal (raw) p-values\n\n- If the test is well calibrated, genes with no real effect (nulls) have p-values spread evenly between 0 and 1.\n  Genes with a real effect pile up near 0.\n  A healthy histogram is therefore a flat floor with a spike at the left edge.\n  The height of the flat part gives a rough sense of how many genes are truly unchanged.expected, before you trust the padj values.\n\n- Uniform shape with no spike: there is little or no signal, or the experiment is underpowered.\n\n- Hill-shaped or skewed toward 1: the test is too conservative.\n  This often points to a wrong variance or dispersion estimate, or to a problem in the pre-filtering.\n\n- A spike near 0 plus an excess of p-values near 1: the model is probably misspecified, for example a missing batch or covariate in the design.\n\n- Strange spikes at specific values: these usually come from low-count genes with discrete p-values.\n  Filtering low-count genes (which the workflow already does) removes most of them.\n\nWhy it matters.\nMultiple testing correction, including Benjamini-Hochberg, assumes the null p-values are uniform.\nIf they aren't, padj and the FDR it promises are unreliable, and the list of significant genes may contain many more false positives, or miss many more real ones, than stated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(deg_table$pvalue)\n```\n\n::: {.cell-output-display}\n![](DESeq2_workflow_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nIn our case the histogram looks perfect - our test is well-calibrated.\n\n## Volcano Plot\n\nenhanced volcano and custom\n",
    "supporting": [
      "DESeq2_workflow_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}